# Generated by Django 5.2.6 on 2025-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_sources',
            field=models.ManyToManyField(blank=True, default=list, related_name='followers', to='aggregator.source'),
        ),
    ]
